### ISSUE TITLE
Notice on code use

### ISSUE THREAD

**Issue by stevefan1999-personal** [explodingcamera/tinywasm#2]
Hey, just a small notice I would be using some of your work here, particularly speaking I'm copying some of your parser code for learning how to write an even smaller WebAssembly interpreter myself. I need to do it because I'm trying to write a simple JIT compiler for WebAssembly but your code is too convoluted to follow and contribute to. If you have any questions please let me know.

**Comment by explodingcamera** [comment]
Hi, sure, no worries. The parser crate specifically is something I plan to completely redo in the future, not a big fan of the wasmparser api at least for my use case. Right now, I'm basically trying to get everything to work before I start simplifying things (Wouldn't be accepting contributions right now anyway, since I'm submitting this for my final project at uni). Good luck on your project!
